import './globals.css';
import Navbar from '../components/Navbar';

export const metadata = {
  title: 'Jujurly - Web Voting',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
